exports.ERR_MSG = {
    INTERNAL_ERROR: "INTERNAL_ERROR",
    EXTERNAL_ERROR: "EXTERNAL_ERROR",
    UNKNOWN_ERROR: "UNKNOWN_ERROR",
    UNEXPECTED_CHARGE_TYPE: "UNEXPECTED_CHARGE_TYPE",

    INVALID_PARAMETER: "INVALID_PARAMETER",
    INVALID_NOWPAYMENTS_KEY: "INVALID_NOWPAYMENTS_KEY",

    NOW_CHECKING: "NOW_CHECKING",

    UNAUTHORIZED: "UNAUTHORIZED",
    BLOCKED_AGENT: "BLOCKED_AGENT",
    INCORRECT_PASSWORD: "INCORRECT_PASSWORD",
    INVALID_PERMISSION: "INVALID_PERMISSION",
    CANNOT_UPDATE_AGENT: "CANNOT_UPDATE_AGENT",
    CANNOT_CREATE_AGENT_LEVEL_UP: "CANNOT_CREATE_AGENT_LEVEL_UP",
    CANNOT_CREATE_AGENT_WITH_ZERO_BALANCE: "CANNOT_CREATE_AGENT_WITH_ZERO_BALANCE",
    SEAMLESS_AGENT_NOT_ALLOWED: "SEAMLESS_AGENT_NOT_ALLOWED",
    TRANSFER_AGENT_NOT_ALLOWED: "TRANSFER_AGENT_NOT_ALLOWED",

    INVALID_AGENT: "INVALID_AGENT",
    INVALID_PARENT_AGENT: "INVALID_PARENT_AGENT",
    INVALID_PARENT_AGENT_TYPE: "INVALID_PARENT_AGENT_TYPE",

    INSUFFICIENT_PARENT_FUNDS: "INSUFFICIENT_PARENT_FUNDS",
    INSUFFICIENT_AGENT_FUNDS: "INSUFFICIENT_AGENT_FUNDS",
    INSUFFICIENT_USER_FUNDS: "INSUFFICIENT_USER_FUNDS",

    INVALID_USER: "INVALID_USER",

    INVALID_ACCESS: "INVALID_ACCESS",

    INVALID_CHECKUP: "INVALID_CHECKUP",
    INVALID_MESSAGE: "INVALID_MESSAGE",
    INVALID_NOTE: "INVALID_NOTE",
    INVALID_POPUP: "INVALID_POPUP",
    INVALID_CONTENT: "INVALID_CONTENT",

    DUPLICATED_AGENT: "DUPLICATED_AGENT",
    SITE_CALLBACK_EMPLTY: "SITE_CALLBACK_EMPLTY",

    INVALID_PROVIDER: "INVALID_PROVIDER",
    INVALID_GAME: "INVALID_GAME",
    INVALID_PLAYER: "INVALID_PLAYER",
    INVALID_CALL: "INVALID_CALL",
    NOT_FOUND_CALL: "NOT_FOUND_CALL",
    PLAYER_BET_CHANGED: "PLAYER_BET_CHANGED",
    CANNOT_APPLY_CALL: "CANNOT_APPLY_CALL",

    EXIST_CALL: "EXIST_PROCESSING_CALL",

    CANNOT_DESTORY_PALYING_CALL : "CANNOT_DESTORY_PALYING_CALL",
};

exports.CHARGE_TYPE = {
    WITHDRAW: 0,
    DEPOSIT: 1,
    DEPOSIT_DIRECT: 2,
    DEPOSIT_AUTOPAY: 3,
}

exports.API_TYPE = {
    SEAMLESS: 0,
    TRANSFER: 1
}
exports.AGENT_TYPE = {
    RESELLER: 1,
    OPERATOR: 2,
    AFFILIATE: 3,
}
exports.AGENT_STATUS = {
    STOPPED: 0,
    SUCCESS: 1,
    DELETED: 2,
}
exports.AGENT_ROLE = {
    NORMAL: 0,
    ADMIN: 1,
    RESELLER_ADMIN: 2,
    CUSTOMER_SERVICE: 3,
    PROTECTOR_DEVELOPER: 4,
    SUPER_ADMIN: 100,
}